name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
commitish: 'v5-develop'
categories:
    -   title: 'Features'
        labels:
            - 'enhancement'
    -   title: 'Bug Fixes'
        labels:
            - 'bug'
    -   title: 'Documentation'
        label: 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    default: major
template: |
    ## Changes

    $CHANGES
