name: Release Drafter

on:
    push:
        branches:
            - v5-development
    pull_request:
        branches:
            - v5-development

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            # Drafts your next Release notes as Pull Requests are merged into the above branches
            - uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-drafter-develop.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
